DROP TABLE IF EXISTS system_master;

CREATE TABLE system_master (
    systemId integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settingKey varchar(255),
    settingValue varchar(255),
    createDateTime timestamp NOT NULL,
    createUser varchar(255) NOT NULL,
    updateDateTime timestamp,
    updateUser varchar(255)
);