DROP TABLE IF EXISTS users;

CREATE TABLE users (
    userId integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userName varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    email1 varchar(255) NOT NULL,
    email2 varchar(255),
    telNo varchar(255),
    deleteFlag smallint NOT NULL,
    authorityFlag smallint NOT NULL,
    createDateTime timestamp NOT NULL,
    createUser varchar(255) NOT NULL,
    updateDateTime timestamp,
    updateUser varchar(255)
);