DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partnerId integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickName varchar(255),
    url varchar(255),
    postNo varchar(8),
    address1 varchar(255),
    address2 varchar(255),
    address3 varchar(255),
    address4 varchar(255),
    partnerName varchar(255),
    memo varchar(255),
    createDateTime timestamp NOT NULL,
    createUser varchar(255) NOT NULL,
    updateDateTime timestamp,
    updateUser varchar(255)
);