DROP TABLE IF EXISTS transactions;

CREATE TABLE transactions (
    transactionId integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partnerId integer NOT NULL,
    transactionPlace varchar(3),
    transactionName varchar(255),
    transactionCategory varchar(3),
    memo varchar(255),
    productId varchar(255),
    transactionKbn smallint,
    transactionDateTime timestamp,
    transactionKYC smallint,
    productAmount integer,
    transactionCost integer,
    shippingWay varchar(1),
    shippingCost integer,
    createDateTime timestamp NOT NULL,
    createUser varchar(255) NOT NULL,
    updateDateTime timestamp,
    updateUser varchar(255),
    CONSTRAINT fk_transactions_partner
    FOREIGN KEY (partnerId) REFERENCES partners(partnerId)
);