DROP TABLE IF EXISTS products;

CREATE TABLE products (
    productId integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionId integer NOT NULL,
    productKbn varchar(3),
    productName varchar(255),
    productFeatures varchar(255),
    createDateTime timestamp NOT NULL,
    createUser varchar(255) NOT NULL,
    updateDateTime timestamp,
    updateUser varchar(255),
    CONSTRAINT fk_products_transaction
    FOREIGN KEY (transactionId) REFERENCES transactions(transactionId)
);