CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT now(),
    UPDATE_DATE TIMESTAMP NOT NULL DEFAULT now(),
    DELETE_DATE TIMESTAMP NULL
);